# Generated by Django 5.1.1 on 2024-10-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primevideo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentObject',
        ),
    ]
