# Generated by Django 5.1.1 on 2024-10-29 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('primevideo', '0003_genre_movie_director_series_director_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'TV Shows'},
        ),
    ]
