# Generated by Django 5.1.1 on 2024-10-30 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primevideo', '0005_alter_series_options_watchedcontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
