# Generated by Django 5.1.1 on 2024-11-08 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primevideo', '0006_movie_watched'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name_plural': 'TV Shows'},
        ),
        migrations.AddField(
            model_name='series',
            name='watched',
            field=models.BooleanField(default=False),
        ),
    ]
