# Generated by Django 5.1.1 on 2024-11-12 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('primevideo', '0008_series_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='user',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='watched',
        ),
        migrations.RemoveField(
            model_name='series',
            name='favorite',
        ),
        migrations.RemoveField(
            model_name='series',
            name='user',
        ),
        migrations.RemoveField(
            model_name='series',
            name='watched',
        ),
        migrations.CreateModel(
            name='UserContentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False)),
                ('favorite', models.BooleanField(default=False)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primevideo.movie')),
                ('series', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='primevideo.series')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='WatchedContent',
        ),
    ]
